name: ytdlp_flutter_android
description: Flutter app to download YouTube videos/audio via Chaquopy Python
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.2.1
  path_provider: ^2.0.15
  permission_handler: ^11.4.0
  percent_indicator: ^4.2.5
