name: ytdlp_flutter_android
description: YouTube downloader using yt-dlp + ffmpeg
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  dynamic_color: ^1.7.0

flutter:
  uses-material-design: true
